package jumpstart.web.pages.examples.navigation;

import jumpstart.web.pages.Index;

import org.apache.tapestry5.ioc.annotations.Inject;
import org.slf4j.Logger;

public class WhatIsCalledAndWhen {

	@Inject
	private Logger _logger;

	void pageLoaded() {
		_logger.debug("   ");
		_logger.debug("pageLoaded()");
	}

	void pageAttached() {
		_logger.debug("   ");
		_logger.debug("pageAttached()");
	}

	void pageDetached() {
		_logger.debug("pageDetached()");
	}

	void onPassivate() {
		_logger.debug("...onPassivate()");
	}

	void onActivate() {
		_logger.debug("...onActivate()");
	}

	void setupRender() {
		_logger.debug("...setupRender()");
	}

	void beginRender() {
		_logger.debug("...beginRender()");
	}

	void afterRender() {
		_logger.debug("...afterRender()");
	}

	void cleanupRender() {
		_logger.debug("...cleanupRender()");
	}

	Object onAction() {
		_logger.debug("...onAction()");
		return Index.class;
	}

	Object onClicked() {
		_logger.debug("...onClicked()");
		return Index.class;
	}

	void onSelected() {
		_logger.debug("...onSelected()");
	}

	void onPrepareForRender() {
		_logger.debug("...onPrepareForRender()");
	}

	void onPrepare() {
		_logger.debug("...onPrepare()");
	}

	void onPrepareForSubmit() {
		_logger.debug("...onPrepareForSubmit()");
	}

	void onValidateForm() {
		_logger.debug("...onValidateForm()");
	}

	void onSuccess() {
		_logger.debug("...onSuccess()");
	}

	void onFailure() {
		_logger.debug("...onFailure()");
	}

	Object onSubmit() {
		_logger.debug("...onSubmit()");
		return Index.class;
	}

	public String getMessage() {
		_logger.debug("...getMessage()");
		return "This message is generated by getMessage().";
	}
}
